alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 24h
    scrapeInterval: 5s
    evaluationInterval: 5s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 192Mi

grafana:
  defaultDashboardsEnabled: false
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/store-dashboard.json
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      cpu: 300m
      memory: 768Mi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      editable: false
      jsonData:
        maxLines: 1000

kube-state-metrics:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
