apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: store
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: store
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 3s
