apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chaosbox

resources:
  - namespace.yaml
  - secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - store-service.yaml
  - store-deployment.yaml
  - store-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: chaosbox
    includeSelectors: false
